### ISSUE TITLE
Use proper UOM for data

### ISSUE THREAD

**Issue by bpaauwe** [sjpbailey/udi-enphase-poly-master-v3#2]
You're using UOM 56 (raw) for the power values.  I believe there is a proper UOM for power (kwh) so you should be using that.

**Comment by sjpbailey** [comment]
Hello Bob,
 I will go through it as I upgraded this version and use the proper UOM’s.
Currently learning and working with Pandas module for data sorting.

Regards

**Comment by sjpbailey** [comment]
All Done Second Release will have new features
